#!/bin/sh -e
#
# chkconfig: S 39 0
#

case "$1" in
	start|restart)
		if [ -e /etc/network/ifstate ]; then
			echo -n "Cleaning: /etc/network/ifstate"
			echo -n >/etc/network/ifstate
			echo "."
		fi
		;;
	stop|reload|force-reload)
		;;
esac
