#!/bin/sh
###############################################################################$
#
# Filename: /etc/init.d/mdev
#
# File Description: Init.d Script to handle dynamic devices with busybox
#
###############################################################################$

[ "$1" != "" ] && action=$1
if [ "$action" = "" ]
then
      echo "Usage: $0 <action  start|stop>" >&2
      exit 1
fi

if [ "$action" = "start" ]
then
	# We need sys and proc to be already mounted
	mount /sys
	mount /proc
	mount -t ramfs none /dev
	mkdir /dev/pts
	mount /dev/pts
	mdev -s
	# Create the needed symbolic links
	ln -sf /proc/self/fd /dev/fd
	ln -sf /proc/self/fd/0 /dev/stdin
	ln -sf /proc/self/fd/1 /dev/stdout
	ln -sf /proc/self/fd/2 /dev/stderr
	# The fb devices can be handled when the device to add is checked
	# on mdev.conf
	mkdir /dev/fb
	ln -sf /dev/fb0 /dev/fb/0
	ln -sf /dev/fb1 /dev/fb/1
	ln -sf /dev/fb2 /dev/fb/2
	ln -sf /dev/fb3 /dev/fb/3
	# Hotplug stuff
	echo "/sbin/mdev" > /proc/sys/kernel/hotplug
fi

exit 0
