#!/bin/sh
#
# Will be used to read /etc/modules.autoload and load modules
# specified there.
#
#
# Filename:/etc/init.d/rc.local
#
# File Description: Auto Start Modules script
#
# @author Thomas Bruno
# @version $Revision: 1.0 $
#
###########################################################

[ "$1" != "" ] && action=$1
if [ "$action" = "" ]
then
      echo "Usage: $0 <action  start|stop>" >&2
      exit 1
fi

if [ "$action" = "start" ]
then
	echo "Will load modules in modules.autoload soon"
else
    if [ "$action" = "stop" ]
    then
	echo "this script does not stop yet"
    fi
fi
