#! /bin/sh
#
# Name: single
# Date: 2003-06-20 16:00
# Author: MontaVista Software, Inc. <source@mvista.com>
# Copyright: Copyright 1999-2003 MontaVista Software, Inc.
# License: 2003 (c) MontaVista Software, Inc. This file is licensed
#          under the terms of the GNU General Public License version 2.
#          This program is licensed "as is" without any warranty of any
#          kind, whether express or implied.
#
# Copyright 2002, 2003, 2004 Sony Corporation
# Copyright 2002, 2003, 2004 Matsushita Electric Industrial Co., Ltd.
#
### BEGIN INIT INFO
# Required-Start: sengsigs 
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: single user init level
# Description: executed by init(8) upon entering runlevel 1 (single).
### END INIT INFO 

# Init script information
INIT_NAME=single
DESC="single-ser mode"

# Individual Daemon information
DAEMON1=/sbin/init
ARGS1="-t1 S"
BASENAME1=${DAEMON1##*/}

. /etc/init.d/init-functions

# Load init script configuration
[ -f /etc/default/$INIT_NAME ] && . /etc/default/$INIT_NAME

# Each init script action is defined below...

log_status_msg "Starting $DESC: " -n
log_status_msg "$BASENAME1" -n
exec $DAEMON1 $ARGS1
