#! /bin/sh
#
# chkconfig: 2345 70 70
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian GNU/Linux
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
# Version:	@(#)skeleton  1.8  03-Mar-1998  miquels@cistron.nl
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/stunnel
NAME=stunnel
DESC="SSL tunnels"
STUNNELCONF=/etc/stunnel.conf

test -f $DAEMON || exit 0

cfgval() {
  sed -n "s/^$1 \\(.*\\)/\\1/p" $STUNNELCONF
}

opts=''
verify=`cfgval VERIFY`
servercert=`cfgval SERVERCERT`
trustedcerts=`cfgval TRUSTEDCERTS`
addlopts=`cfgval ADDLOPTS`
[ -n "$verify" ] && opts="$opts -v $verify"
[ -n "$servercert" ] && opts="$opts -p $servercert"
[ -n "$trustedcerts" ] && opts="$opts -a $trustedcerts"
[ -n "$addlopts" ] && opts="$opts $addlopts"

set -e

case "$1" in
  start)
	echo -n "Starting $DESC:"
	cfgval TUNNEL | while read serv prog; do
		echo -n " $serv"
		$DAEMON -P /var/run/stunnel.$serv.pid $opts -d $serv $prog
	done
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC:"
	cfgval TUNNEL | while read serv prog; do
		echo -n " $serv"
		start-stop-daemon --stop --quiet \
			--pidfile /var/run/stunnel.$serv.pid \
			--exec $DAEMON -- $opts -d $serv $prog
	done
	echo "."
	;;
  #reload)
	#
	#	If the daemon can reload its config files on the fly
	#	for example by sending it SIGHUP, do it here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this a do-nothing entry.
	#
	# echo "Reloading $DESC configuration files."
	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
	#	/var/run/$NAME.pid --exec $DAEMON
  #;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	$0 stop
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
