#!/bin/sh
#
# Load TI modules and create their devices.
# Will go away as soon as we figure how to load modules automatically.
#
# Filename:/etc/init.d/ti-modules
#
# File Description: Load TI modules and create their devices.
#
# @author Ugo Riboni
# @version $Revision: 1.0 $
#
###########################################################

[ "$1" != "" ] && action=$1
if [ "$action" = "" ]
then
	echo "Usage: $0 <action  start|stop>" >&2
	exit 1
fi

if [ "$action" = "start" ]
then
	echo "Loading DSP support modules"

	# make /dev/cmem
	rm -f /dev/cmem
	mknod /dev/cmem c `awk "\\$2==\"cmem\" {print \\$1}" /proc/devices` 0
	
	# make /dev/dsplink
	rm -f /dev/dsplink
	mknod /dev/dsplink c `awk "\\$2==\"dsplink\" {print \\$1}" /proc/devices` 0
else
	if [ "$action" = "stop" ]
	then
		rm -f /dev/dsplink
		rm -f /dev/cmem
		rmmod dsplink
		rmmod cmem
	fi
fi
