#! /bin/sh
#
# Name: xinetd 
# Date: 2003-06-27 19:40
# Author: MontaVista Software, Inc. <source@mvista.com>
# Copyright: Copyright 1999-2003 MontaVista Software, Inc.
# License: 2003 (c) MontaVista Software, Inc. This file is licensed
#          under the terms of the GNU General Public License version 2.
#          This program is licensed "as is" without any warranty of any
#          kind, whether express or implied.
# 
# Copyright 2002, 2003, 2004 Sony Corporation
# Copyright 2002, 2003, 2004 Matsushita Electric Industrial Co., Ltd.
#
### BEGIN INIT INFO
# Required-Start: 
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start/stop xinetd
# Description: script to start and stop xinetd
### END INIT INFO 
# chkconfig: 2345 20 20

# Init script information
INIT_NAME=xinetd
DESC="internet superserver"

# Individual Daemon information
DAEMON1=/usr/sbin/xinetd-ipv4
ARGS1="-reuse"
BASENAME1=${DAEMON1##*/}
DAEMON2=/usr/bin/rpcinfo
ARGS2="-u localhost portmapper"

# Load init script configuration
[ -f /etc/default/$INIT_NAME ] && . /etc/default/$INIT_NAME

# Source the init script functions
. /etc/init.d/init-functions

# Verify daemons are installed
[ "$1" = "status" ] && NFOUND=4 || NFOUND=5
test -f $DAEMON1 -a -f $DAEMON2 || exit $NFOUND

# Each init script action is defined below...

start() {
	local RET ERROR=
	
	if grep "^[^ *#]" /etc/xinetd.conf | grep -q 'rpc/'
	then
		if ! $DAEMON2 $ARGS2 >/dev/null 2>&1; then
      			log_status_msg ""
      			log_status_msg "WARNING: portmapper inactive - RPC services unavailable!"
      			log_status_msg "    Commenting out or removing the RPC services from"
      			log_status_msg "    the /etc/xinetd.conf file will remove this message."
      			log_status_msg
    		fi
  	fi
	log_status_msg "Starting $DESC: " -n
	log_status_msg "$BASENAME1" -n
	start_daemon $DAEMON1 $ARGS1
	RET=$?
	if [ $RET -eq 0 ]; then
		log_success_msg "."n
	else
		log_failure_msg " failed ($RET: $ERROR)."
		return 1
	fi
	
	log_status_msg ""
	return 0
}

stop () {
	local RET ERROR=

	log_status_msg "Stopping $DESC: " -n
	log_status_msg "$BASENAME1" -n
	killproc $BASENAME1 -3
	RET=$?
	if [ $RET -eq 0 ]; then
		log_success_msg ". "
	else
		log_failure_msg "failed ($RET: $ERROR). " -n
		return 1
	fi

	log_status_msg ""
	return 0
}

restart() {
	local RET

	log_status_msg "Restarting $DESC..."
	stop
	start
	RET=$?

	return $RET
}

tryrestart() {
	local RET

	pidstatus $BASENAME1
	RET=$?
	if [ $RET -eq 0 ]; then
		restart
		RET=$?
	else
		RET=7
	fi

	return $RET
}

#
# if the service does not support reload return code 3 should
# be the result...
#
reload() {
	local RET
	log_status_msg "Reloading $DESC configuration" -n
	log_status_msg "BASENAME1" -n
	killproc $BASENAME1 -10
	if [ $RET -eq 0 ]; then
                log_success_msg "done." -n
        else
                log_failure_msg "failed ($RET: $ERROR). " -n
                return 1
    fi

	return $RET
}

forcereload() {
	local RET

	log_status_msg "Forcefully reloading $DESC configuration" -n
        log_status_msg "BASENAME1" -n
        killproc $BASENAME1 -12
        if [ $RET -eq 0 ]; then
                log_success_msg "done." -n
        else
                log_failure_msg "failed ($RET: $ERROR). " -n
                return 1
  fi
	
	return $RET
} 

status() {
	local RET
	
	printstatus $BASENAME1
	RET=$?

	return $RET
}

#
# Everything after this should be the same for all init scripts
#
# See the policy manual for information on actions and return codes.
#

parse() {
	case "$1" in
    start)
			start
			return $?
	;;
    stop)
			stop
			return $?
			;;
		restart)
			restart
			return $?
			;;
		try-restart)
			tryrestart
			return $?
	;;
    reload)
			reload
			return $?
	;;
    force-reload)
			forcereload
			return $?
	;;
		status)
			status
			return $?
	;;
    *)
			echo "Usage: $INIT_NAME " \
			"{start|stop|restart|try-restart|reload|" \
			"force-reload|status}" >&2
	;;
	esac
	
	return 1
}

parse $@

